config/routes.rb
Rails.application.routes.draw do

  get 'career/index'
  get 'career/show'

  root 'main#index'
  get 'main/index'
  get 'main/search'

  get 'ranking/index'
  get 'ranking/show'

  get 'trend/index'
  get 'trend/show'


  resources :services

  resources :companies do
    member do
      get '/detail' => 'companies#detail'
    end
  end

  resources :company_fields do
    member do
    end
  end

  resources :stacks do
    member do
      post '/register_interesting' => 'stacks#register_interesting', as: 'register_inter'
      post '/register_my_stack' => 'stacks#register_my_stack', as: 'register_my'
    end
    collection do
      get '/add_stack' => 'stacks#add_stack', as: 'add_my'
    end
  end

  resources :stack_fields

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :admin do
    resources :users do
    end
  end

  namespace :enter do
    resources :companies do
      resources :services do
        member do
          get '/add_stack' => 'services#add_stack', as: 'add_stack_to'
        end
        collection do
          post '/regist_stack' => 'services#regist_stack', as: 'register_stack'
          delete '/delete_stack' => 'services#delete_stack', as: 'delete_stack_to'
        end
      end
    end
  end

  namespace :indi do
    post '/regist_stack' => 'users#regist_stack', as: 'register_stack'
    resources :users do
      collection do
        get '/add_stack' => 'users#add_stack', as: 'add_my'
      end
    end
  end










end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :company

  #has_and_belongs_to_many :stacks
  #mount_uploader :logo_url, ServiceLogoUploader

  has_many :impressions, :as=> :impressionable

  has_many :services, through: :service_stacks
  has_many :services_stack

   def impression_count
       impressions.size
   end

   def unique_impression_count
       # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
       # so getting keys from the hash and calculating the number of keys
       impressions.group(:ip_address).size.keys.length #TESTED
   end
end

app/controllers/enter/application_controller.rb
class Enter::ApplicationController < ApplicationController
  before_action :check_admin
  layout 'enter'   #layout밑의 admin템플릿을 쓰겠다.


  private
  def check_admin
    #지금 접속한 친구가 관리자인지 판별
    #아닐 경우 root페이지
    # if current_user.enter?
    #   puts current_user.enter?
    #   redirect_to stacks_path
    # end

    unless user_signed_in? && current_user.enter?
      redirect_to(root_path, alert: '기업회원만 접근가능합니다.')
    end
  end
end

app/controllers/enter/companies_controller.rb
class Enter::CompaniesController < Enter::ApplicationController
  before_action :set_company, only: [:index,:show, :edit, :update, :destroy]


  def index
    # @services = Service.all
    # @user = current_user
    # @company = Company.find_by(id: current_user.company_id)
    @services = Service.where(company_id: @company.id)
  end

  def show
    @services = Service.where(company_id: @company.id)
  end
  def new
    @company = Company.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to "/enter/companies/#{@company.id}", notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :site_url, :logo_url, :describe, :company_field_id)
    end

end

app/controllers/enter/services_controller.rb
class Enter::ServicesController < Enter::ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy, :add_stack]
  # GET /services
  # GET /services.json
  def index
    @company = Company.find_by(params[:id])
    @services = Service.where(company_id: params[:id])
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @stacks = ServiceStack.where(service_id: @service.id)
  end

  # GET /services/new
  def new
    @service = Service.new
    # @stacks = Stack.all
    @company = Company.find_by(params[:id])
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    respond_to do |format|
      if @service.save   #/enter/companies/:company_id/services/:id/add_stack
        format.html { redirect_to "/enter/companies/#{@service.company_id}/services/#{@service.id}/add_stack", notice: 'Service was successfully created.' }
        format.json { render :add_stack, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to "/enter/companies/#{@service.company_id}/services/#{@service.id}",method: :get, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    authorize! :destroy, @service
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_stack
    @stack_fields = StackField.all
  end

  def regist_stack
    # @st = Service.find_by(name: @service.name)
    stack_list = params[:return_val]
    service_id = params[:service_id]
    stack_list.each do |st|
        check = ServiceStack.where(service_id: service_id).where(stack_id: st).exists?
        unless check
          ServiceStack.create(
            service_id: service_id,
            stack_id: st
          )
        end
    end
    redirect_to enter_company_service_path(current_user.company_id, service_id)
  end

  def delete_stack
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :site_url, :logo_url, :describe, :company_id)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :log_impression, :only=> [:show]

  def log_impression
    @hit_post = Service.find(params[:id])
    # this assumes you have a current_user method in your authentication system
    @hit_post.impressions.create(ip_address: request.remote_ip)
  end
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @stacks = ServiceStack.where(service_id: @service.id)
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
    authorize! :edit, @service.id
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :site_url, :logo_url, :describe, :company_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/enter/services/_form.html.erb
<%= form_for(@service, url: enter_company_service_path(@service.company_id, @service), method: :patch) do |f| %>  <!--, url: "/enter/companies/#{@company.id}/services/#{@service.id}/add_stack", method: :get-->
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.file_field :logo_url%>
  </div>
  <div class="field">
    <%= f.label :describe %><br>
    <%= f.text_area :describe %>
  </div>
  <%= f.hidden_field :company_id, id:"company_id"%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $(function(){
    // console.log(<%#=@company.id%>)
    $('#company_id').val(<%=current_user.company_id%>);
  })
</script>

app/views/enter/services/_form_create.html.erb
<%= form_for(@service, url: enter_company_services_path(@company.id), method: :post) do |f| %>  <!--, url: "/enter/companies/#{@company.id}/services/#{@service.id}/add_stack", method: :get-->
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.file_field :logo_url%>
  </div>
  <div class="field">
    <%= f.label :describe %><br>
    <%= f.text_area :describe %>
  </div>
  <%= f.hidden_field :company_id, id:"company_id"%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $(function(){
    // console.log(<%#=@company.id%>)
    $('#company_id').val(<%=current_user.company_id%>);
  })
</script>

app/views/enter/services/add_stack.erb
<input type="button" value = "등록" id="aa"><br>
<%#= link_to 'submit', enter_company_service_path(current_user.company_id, @service.id), method: :get, :onclick => "$('#aa').submit()"  %>

<% @stack_fields.each do |field|%>


  <div class="container" style="height: 180px;">
  <h5><%= field.name%></h5>
  <% field.stacks.each do |stack| %>
    <div style="height:50px;width:50px; float:left; margin:5px">
      <img class="img" src="https://s3.ap-northeast-2.amazonaws.com/dahisy-4th-project/Stack/<%=field.name%>/<%= stack.name.capitalize %>.png", id= "<%= stack.id%>", width="50">
      <%=hidden_field_tag "", current_user.my?(stack), class: "cb", stack_id: stack.id%>
    </div>
  <% end %>
  </div>

<% end %>


<script>
$(function(){
  $(".cb").each(function(){
    if($(this).val() == "true"){
        $(this).parent("div").css("border","2px solid red");
    }
  })
  $(".img").on("click",function(){
    console.log()
    var value = $(this).siblings(".cb").val()
    if(value == "true"){
      $(this).siblings(".cb").val("false")
      $(this).parent("div").css("border","0px");
    }else{
      $(this).siblings(".cb").val("true")
      $(this).parent("div").css("border","2px solid red");
    }
  })
  $("#aa").on("click", function(){
    var ret = []
    $(".cb[value=true]").each(function(){
      ret.push($(this).attr("stack_id"))
    });
    console.log(ret);

    $.ajax({
      url: "<%= register_stack_enter_company_services_path %>",
      method: "POST",
      data: {return_val : ret, service_id : <%=@service.id%>}
    });
  });
})
</script>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

app/views/enter/services/edit.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Back', url: "/enter/companies/#{current_user.company_id}/services/#{@service.id}" %>

app/views/enter/services/new.erb
<h1>새 서비스 form</h1>

<%= render 'form_create' %>



<%= link_to 'Back', enter_companies_path(@company) %>

app/views/enter/services/show.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Site url:</strong>
  <%= @service.site_url %>
</p>

<p>
  <strong>Logo url:</strong>
  <%= @service.logo_url %>
</p>

<p>
  <strong>Describe:</strong>
  <%= @service.describe %>
</p>

<p>
  <strong>Company:</strong>
  <%= @service.company.name %>
</p>

<p>
  <strong>Stack:</strong><br>
  <% @stacks.each do |r|%>
    <a href="/stacks/<%=r.stack.id%>">
      <img src="https://s3.ap-northeast-2.amazonaws.com/dahisy-4th-project/Stack/<%=r.stack.stack_field.name%>/<%= r.stack.name.capitalize %>.png" width="40">
    </a>
  <% end %>
</p>

<%= link_to 'Edit', "/enter/companies/#{@service.company_id}/services/#{@service.id}/edit" %> |
<%= link_to 'Delete', "/enter/companies/#{@service.company_id}/services/#{@service.id}", method: :delete %> |
<%= link_to 'Back', enter_company_path(@service.company_id) %>