config/routes.rb
Rails.application.routes.draw do

  get 'career/index'
  get 'career/show'

  root 'main#index'
  get 'main/index'
  get 'main/search'

  get 'ranking/index'
  get 'ranking/show'

  get 'trend/index'
  get 'trend/show'


  resources :services

  resources :companies do
    member do
      get '/detail' => 'companies#detail'
    end
  end

  resources :company_fields do
    member do
    end
  end

  resources :stacks do
    member do
      post '/register_interesting' => 'stacks#register_interesting', as: 'register_inter'
      post '/register_my_stack' => 'stacks#register_my_stack', as: 'register_my'
    end
    collection do
      get '/add_stack' => 'stacks#add_stack', as: 'add_my'
    end
  end

  resources :stack_fields

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :admin do
    resources :users do
    end
  end

  namespace :enter do
    resources :companies do
      resources :services do
        member do
          get '/add_stack' => 'services#add_stack', as: 'add_stack_to'
        end
        collection do
          post '/regist_stack' => 'services#regist_stack', as: 'register_stack'
          delete '/delete_stack' => 'services#delete_stack', as: 'delete_stack_to'
        end
      end
    end
  end

  namespace :indi do
    post '/regist_stack' => 'users#regist_stack', as: 'register_stack'
    resources :users do
      collection do
        get '/add_stack' => 'users#add_stack', as: 'add_my'
      end
    end
  end










end

app/models/stack.rb
class Stack < ActiveRecord::Base
  belongs_to :stack_field

  has_and_belongs_to_many :users
  has_and_belongs_to_many :services
  resourcify

  has_many :impressions, :as=>:impressionable

  def impression_count
      impressions.size
  end

  def unique_impression_count
      # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
      # so getting keys from the hash and calculating the number of keys
      impressions.group(:ip_address).size.keys.length #TESTED
  end

end

app/controllers/admin/stacks_controller.rb
class Admin::StacksController < Admin::ApplicationController
  def index
    @stacks = Stack.all
  end


end

app/controllers/stacks_controller.rb
class StacksController < ApplicationController
  before_action :set_stack, only: [:show, :edit, :update, :destroy, :register_interesting, :register_my_stack]
  before_action :log_impression, :only=> [:show]

 def log_impression
    @hit_post = Stack.find(params[:id])
    # this assumes you have a current_user method in your authentication system
    @hit_post.impressions.create(ip_address: request.remote_ip)
 end

  # GET /stacks
  # GET /stacks.json
  def index
    @stacks = Stack.all
    @stack_fields = StackField.all
  end

  # GET /stacks/1
  # GET /stacks/1.json
  def show
    # 해당 스택을 사용하는 서비스 리스트 보여주기
    # @result_companies = Company.where("name Like ?", "%#{params[:search]}%")
    if user_signed_in?
      @like_my = MyStack.where(user_id: current_user.id).where(stack_id: @stack.id).exists?
      @like_inter = InterStack.where(user_id: current_user.id).where(stack_id: @stack.id).exists?
    end
    @edu_paths = EduPath.where(stack_id: @stack.id)
    @services = ServiceStack.where(stack_id: @stack.id)
    @edu_paths = EduPath.where(stack_id: @stack.id)
  end

  # GET /stacks/new
  def new
    @stack = Stack.new
  end

  # GET /stacks/1/edit
  def edit
    authorize! :edit, @stack.id
  end

  def add_stack
    @stacks = Stack.all
    @stack = Stack.all.to_a
    @stack_fields = StackField.all
  end

  # POST /stacks
  # POST /stacks.json
  def create
    @stack = Stack.new(stack_params)

    respond_to do |format|
      if @stack.save
        format.html { redirect_to @stack, notice: 'Stack was successfully created.' }
        format.json { render :show, status: :created, location: @stack }
      else
        format.html { render :new }
        format.json { render json: @stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stacks/1
  # PATCH/PUT /stacks/1.json
  def update
    respond_to do |format|
      if @stack.update(stack_params)
        format.html { redirect_to @stack, notice: 'Stack was successfully updated.' }
        format.json { render :show, status: :ok, location: @stack }
      else
        format.html { render :edit }
        format.json { render json: @stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stacks/1
  # DELETE /stacks/1.json
  def destroy
    @stack.destroy
    respond_to do |format|
      format.html { redirect_to stacks_url, notice: 'Stack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def register_interesting
    if user_signed_in?
      if InterStack.where(user_id: current_user.id, stack_id: @stack.id).first.nil?
        @result = InterStack.create(user_id: current_user.id, stack_id: @stack.id)
      else
        @result = InterStack.where(user_id: current_user.id, stack_id: @stack.id).first.destroy
      end
      @result = @result.frozen?
    end
  end

  def register_my_stack
    if user_signed_in?
      if MyStack.where(user_id: current_user.id, stack_id: @stack.id).first.nil?
        @result = MyStack.create(user_id: current_user.id, stack_id: @stack.id)
      else
        @result = MyStack.where(user_id: current_user.id, stack_id: @stack.id).first.destroy
      end
      @result = @result.frozen?
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stack
      @stack = Stack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stack_params
      params.require(:stack).permit(:name, :site_url, :short_describe, :describe, :version, :stack_field_id)
    end
end

app/helpers/stacks_helper.rb
module StacksHelper
end

app/views/stacks/_form.html.erb
<%= form_for(@stack) do |f| %>
  <% if @stack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stack.errors.count, "error") %> prohibited this stack from being saved:</h2>

      <ul>
      <% @stack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :short_describe %><br>
    <%= f.text_field :short_describe %>
  </div>
  <div class="field">
    <%= f.label :describe %><br>
    <%= f.text_area :describe %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :stack_field_id %><br>
    <%= f.text_field :stack_field_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stacks/add_stack.erb
<input type="button" value = "등록" id="aa">

<% @stack_fields.each do |field|%>
  <p>
    <a class="btn btn-link" data-toggle="collapse" href="#<%=field.name %>" aria-expanded="false" aria-controls="collapseExample">
      <%= field.name%>
    </a>
  </p>
  <div id="<%= field.name%>">
    <div class="card card-body">
    <% field.stacks.each do |stack| %>
    <div style="width:50px; height:50; float:left; margin-right:10px;">
      <img class="img" src="https://s3.ap-northeast-2.amazonaws.com/dahisy-4th-project/Stack/<%=stack.stack_field.name%>/<%= stack.name.capitalize %>.png", id= "<%= stack.id%>", width="50">
      <%=hidden_field_tag "", current_user.my?(stack), class: "cb", stack_id: stack.id%>
      </div>
      <% end %>
    </div>

<% end %>


<script>
$(function(){
  $(".cb").each(function(){
    if($(this).val() == "true"){
        $(this).parent("div").css("border","1px solid red");
    }
  })
  $(".img").on("click",function(){
    console.log()
    var value = $(this).siblings(".cb").val()
    if(value == "true"){
      $(this).siblings(".cb").val("false")
      $(this).parent("div").css("border","0px");
    }else{
      $(this).siblings(".cb").val("true")
      $(this).parent("div").css("border","1px solid red");
    }
  })
  $("#aa").on("click", function(){
    var ret = []
    $(".cb[value=true]").each(function(){
      ret.push($(this).attr("stack_id"))
    });
    console.log(ret);
    $.ajax({
      url: "<%= indi_register_stack_path %>",
      method: "POST",
      data: {return_val : ret}
    });
  });
})
</script>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

app/views/stacks/edit.html.erb
<h1>Editing Stack</h1>

<%= render 'form' %>

<%= link_to 'Show', @stack %> |
<%= link_to 'Back', stacks_path %>

app/views/stacks/new.html.erb
<h1>New Stack</h1>

<%= render 'form' %>

<%= link_to 'Back', stacks_path %>

app/views/stacks/register_interesting.js.erb
if(<%= @result%>){
  alert("등록 취소");
  $('#inter_button').addClass("btn-primary").removeClass("btn-success");
}else{
  alert("등록 완료");
  $('#inter_button').addClass("btn-success").removeClass("btn-primary");
}

app/views/stacks/register_my_stack.js.erb
if(<%= @result%>){
  alert("등록 취소");
  $('#my_button').addClass("btn-primary").removeClass("btn-success");
}else{
  alert("등록 완료");
  $('#my_button').addClass("btn-success").removeClass("btn-primary");
}

app/views/stacks/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<div class="container">

  <% if user_signed_in? && current_user.admin? %>
    <%= link_to 'Edit', edit_stack_path(@stack) %> |
  <% end %>
    <%= link_to ' Back', url_for(:back), class: "fa fa-angle-left fa-1x"  %><br><br>

  <h2><%= @stack.name.capitalize %></h2>
  <%= @stack.version %>v
  조회수 : <%= "#{@hit_post.unique_impression_count}" %>
  <br>
  <p>
    <img src="https://s3.ap-northeast-2.amazonaws.com/dahisy-4th-project/Stack/<%=@stack.stack_field.name%>/<%= @stack.name.capitalize %>.png" width="100">
    <br><br>
    <!-- 관심스택 등록 버튼 -->
    <%if user_signed_in?%>
      <% if current_user.indi? %>
        <% if @like_inter %>
          <button type="button" class="btn btn-success btn-pill" id= "inter_button">관심스택</button>
        <% else %>
          <button type="button" class="btn btn-primary btn-pill" id= "inter_button">관심스택</button>
        <% end %>
        <!-- 마이스택 등록 버튼 -->
        <% if @like_my %>
          <button type="button" class="btn btn-success btn-pill" id= "my_button">마이스택</button>
        <% else %>
          <button type="button" class="btn btn-primary btn-pill" id= "my_button">마이스택</button>
        <% end %>
      <% end %>
    <% end %>
  </p>


<p>
  <strong>Site url:</strong>
  <%= @stack.site_url %>
</p>

<p>
  <%= @stack.describe %>
</p>

<p>
  <strong>Stack field:</strong>
  <%= @stack.stack_field.name %>
</p>

<p>
  <strong>이 스택을 사용하는 서비스들:</strong><br>
  <% @services.each do |s| %>
  <button type="button" class="btn btn-outline-primary btn-pill">
    <%= s.service.name %>
    </button>
  <% end %>
</p>

<p>

  <strong>스택 교육 사이트:</strong><br>
  <% @edu_paths.each do |s| %>
    <a href="<%=s.url%>" target="_blank" class="fa fa-pencil fa-1x"><%= s.url %></a><br>
  <% end %>
</p>

</div>

<script>
  $(function(){
    $('#inter_button').on('click',function(e){
      e.preventDefault();
      $.ajax({
        url: "<%= register_inter_stack_path%>",
        method: "POST",
        data: "<%=@stack%>"
      })
    });

    $('#my_button').on('click', function(e){
      e.preventDefault();
      $.ajax({
        url: "<%=register_my_stack_path%>",
        method: "POST",
        data: "<%=@stack%>"
      });
    });
  })
</script>