config/routes.rb
Rails.application.routes.draw do

  get 'career/index'
  get 'career/show'

  root 'main#index'
  get 'main/index'
  get 'main/search'

  get 'ranking/index'
  get 'ranking/show'

  get 'trend/index'
  get 'trend/show'


  resources :services

  resources :companies do
    member do
      get '/detail' => 'companies#detail'
    end
  end

  resources :company_fields do
    member do
    end
  end

  resources :stacks do
    member do
      post '/register_interesting' => 'stacks#register_interesting', as: 'register_inter'
      post '/register_my_stack' => 'stacks#register_my_stack', as: 'register_my'
    end
    collection do
      get '/add_stack' => 'stacks#add_stack', as: 'add_my'
    end
  end

  resources :stack_fields

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :admin do
    resources :users do
    end
  end

  namespace :enter do
    resources :companies do
      resources :services do
        member do
          get '/add_stack' => 'services#add_stack', as: 'add_stack_to'
        end
        collection do
          post '/regist_stack' => 'services#regist_stack', as: 'register_stack'
          delete '/delete_stack' => 'services#delete_stack', as: 'delete_stack_to'
        end
      end
    end
  end

  namespace :indi do
    post '/regist_stack' => 'users#regist_stack', as: 'register_stack'
    resources :users do
      collection do
        get '/add_stack' => 'users#add_stack', as: 'add_my'
      end
    end
  end










end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :company_field
  has_many :services
  resourcify
  #mount_uploader :logo_url, CompanyLogoUploader
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::ApplicationController
  def index
    @companies = Company.all
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :detail]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @services = Service.where(company_id: @company.id)
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    authorize! :edit, @company.id
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    ret = @company.save

    respond_to do |format|
      if ret
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def detail
    @services = Service.where(company_id: @company.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :site_url, :logo_url, :describe, :company_field_id)
    end
end

app/controllers/enter/companies_controller.rb
class Enter::CompaniesController < Enter::ApplicationController
  before_action :set_company, only: [:index,:show, :edit, :update, :destroy]


  def index
    # @services = Service.all
    # @user = current_user
    # @company = Company.find_by(id: current_user.company_id)
    @services = Service.where(company_id: @company.id)
  end

  def show
    @services = Service.where(company_id: @company.id)
  end
  def new
    @company = Company.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to "/enter/companies/#{@company.id}", notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :site_url, :logo_url, :describe, :company_field_id)
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.text_field :logo_url%>
  </div>
  <div class="field">
    <%= f.label :describe %><br>
    <%= f.text_area :describe %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/detail.erb
<p id="notice"><%= notice %></p>
<nav aria-label="breadcrumb" role="navigation">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/company_fields"><%= @company.company_field.name%></a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @company.name %></li>
  </ol>
</nav>


<div class="container">

<div class="media">
  <img src="<%=@company.logo_url%>" title="<%=@company.name%>" id: "#{@company.name}" size=200>
  <div class="media-body">
    <h5 class="mt-0"><%= @company.name %></h5>
    <%= @company.site_url %>
  </div>
</div>

<br>

<p class="text-xl-left"><%= @company.describe %></p>

<br>
<p>
  <strong><%=@company.name%>의 서비스</strong><br><br>
  <% @services.each do |service| %>
  <%= link_to "<button type='button' class='btn btn-outline-primary btn-pill'>#{service.name}</button>".html_safe, "/services/#{service.id}" %></td>
  <% end %>
</p>
<br><br>
<%= link_to 'Back', company_field_path(@company.company_field_id) %>
</div>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Site url</th>
      <th>Logo url</th>
      <th>Describe</th>
      <th>Company field</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.site_url %></td>
        <td><%= company.logo_url %></td>
        <td><%= company.describe %></td>
        <td><%= company.company_field %></td>
        <td><%= link_to 'Show', company %></td>
        <% if user_signed_in? &&  current_user.admin? %>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? &&  current_user.admin? %>
<%= link_to 'New Company', new_company_path %>
<% end %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Company Details</h1>

<br>

<%= @company.name %><br>
<%= @company.site_url %><br>
<img src="<%=@company.logo_url%>" data-toggle="tooltip" title="<%=@company.name%>" id: "#{@company.name}"><br>
<%= @company.describe %><br><br><br>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>
    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.name %><%= link_to '<button type="button">상세보기</button>'.html_safe, "/services/#{service.id}" %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<%= link_to 'Back', company_field_path(@company.company_field_id) %>