config/routes.rb
Rails.application.routes.draw do

  get 'career/index'
  get 'career/show'

  root 'main#index'
  get 'main/index'
  get 'main/search'

  get 'ranking/index'
  get 'ranking/show'

  get 'trend/index'
  get 'trend/show'


  resources :services

  resources :companies do
    member do
      get '/detail' => 'companies#detail'
    end
  end

  resources :company_fields do
    member do
    end
  end

  resources :stacks do
    member do
      post '/register_interesting' => 'stacks#register_interesting', as: 'register_inter'
      post '/register_my_stack' => 'stacks#register_my_stack', as: 'register_my'
    end
    collection do
      get '/add_stack' => 'stacks#add_stack', as: 'add_my'
    end
  end

  resources :stack_fields

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :admin do
    resources :users do
    end
  end

  namespace :enter do
    resources :companies do
      resources :services do
        member do
          get '/add_stack' => 'services#add_stack', as: 'add_stack_to'
        end
        collection do
          post '/regist_stack' => 'services#regist_stack', as: 'register_stack'
          delete '/delete_stack' => 'services#delete_stack', as: 'delete_stack_to'
        end
      end
    end
  end

  namespace :indi do
    post '/regist_stack' => 'users#regist_stack', as: 'register_stack'
    resources :users do
      collection do
        get '/add_stack' => 'users#add_stack', as: 'add_my'
      end
    end
  end










end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :company_field
  has_many :services
  resourcify
  #mount_uploader :logo_url, CompanyLogoUploader
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::ApplicationController
  def index
    @companies = Company.all
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :detail]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @services = Service.where(company_id: @company.id)
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    authorize! :edit, @company.id
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    ret = @company.save

    respond_to do |format|
      if ret
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def detail
    @services = Service.where(company_id: @company.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :site_url, :logo_url, :describe, :company_field_id)
    end
end

app/controllers/enter/application_controller.rb
class Enter::ApplicationController < ApplicationController
  before_action :check_admin
  layout 'enter'   #layout밑의 admin템플릿을 쓰겠다.


  private
  def check_admin
    #지금 접속한 친구가 관리자인지 판별
    #아닐 경우 root페이지
    # if current_user.enter?
    #   puts current_user.enter?
    #   redirect_to stacks_path
    # end

    unless user_signed_in? && current_user.enter?
      redirect_to(root_path, alert: '기업회원만 접근가능합니다.')
    end
  end
end

app/controllers/enter/companies_controller.rb
class Enter::CompaniesController < Enter::ApplicationController
  before_action :set_company, only: [:index,:show, :edit, :update, :destroy]


  def index
    # @services = Service.all
    # @user = current_user
    # @company = Company.find_by(id: current_user.company_id)
    @services = Service.where(company_id: @company.id)
  end

  def show
    @services = Service.where(company_id: @company.id)
  end
  def new
    @company = Company.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to "/enter/companies/#{@company.id}", notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :site_url, :logo_url, :describe, :company_field_id)
    end

end

app/controllers/enter/services_controller.rb
class Enter::ServicesController < Enter::ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy, :add_stack]
  # GET /services
  # GET /services.json
  def index
    @company = Company.find_by(params[:id])
    @services = Service.where(company_id: params[:id])
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @stacks = ServiceStack.where(service_id: @service.id)
  end

  # GET /services/new
  def new
    @service = Service.new
    # @stacks = Stack.all
    @company = Company.find_by(params[:id])
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    respond_to do |format|
      if @service.save   #/enter/companies/:company_id/services/:id/add_stack
        format.html { redirect_to "/enter/companies/#{@service.company_id}/services/#{@service.id}/add_stack", notice: 'Service was successfully created.' }
        format.json { render :add_stack, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to "/enter/companies/#{@service.company_id}/services/#{@service.id}",method: :get, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    authorize! :destroy, @service
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_stack
    @stack_fields = StackField.all
  end

  def regist_stack
    # @st = Service.find_by(name: @service.name)
    stack_list = params[:return_val]
    service_id = params[:service_id]
    stack_list.each do |st|
        check = ServiceStack.where(service_id: service_id).where(stack_id: st).exists?
        unless check
          ServiceStack.create(
            service_id: service_id,
            stack_id: st
          )
        end
    end
    redirect_to enter_company_service_path(current_user.company_id, service_id)
  end

  def delete_stack
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :site_url, :logo_url, :describe, :company_id)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/enter/companies/_form.html.erb
<%= form_for(@company, url: enter_company_path(@company), method: :patch) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.text_field :logo_url %>
  </div>
  <div class="field">
    <%= f.label :describe %><br>
    <%= f.text_area :describe %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enter/companies/edit.erb
<h1>회사 정보 수정 form</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', enter_companies_path %>

app/views/enter/companies/index.erb
<h1>회사 관리 페이지</h1>
이메일 : <%= @user.email%><br>
이름 : <%= @user.nickname%><br>
권한 : <%= @user.role%><br>
전화번호 : <%= @user.phone%><br>
<%= link_to '수정', edit_user_registration_path %>

<br><br>

<h1>회사 정보</h1>
회사 명: <%= @company.name%><br>
회사 주소: <%= @company.site_url%><br>

<%= link_to '수정', edit_enter_company_path(@company)%>

<br><br>

<h1>서비스 정보</h1>
<%= link_to 'new', "/enter/companies/#{@company.id}/services/new"%>
<% if @services %>
  <% @services.each do |service|%>
    <%= service.name%>
  <% end %>
<% end %>
<%= link_to '추가', new_enter_company_service_path(@company)%>

app/views/enter/companies/show.erb
<h1>회사 관리 페이지</h1>
이메일 : <%= current_user.email%><br>
이름 : <%= current_user.nickname%><br>
권한 : <%= current_user.role%><br>
전화번호 : <%= current_user.phone%><br>
<%= link_to '수정', edit_user_registration_path %>

<br><br>

<h1>회사 정보</h1>
회사 명: <%= @company.name%><br>
회사 주소: <%= @company.site_url%><br>
회사 내용: <%= @company.describe%><br>
<%= link_to '수정', edit_enter_company_path(@company)%>

<br><br>

<h1>서비스 정보!</h1>
<%= link_to 'new', "/enter/companies/#{@company.id}/services/new"%><br>
<% if @services %>
  <% @services.each do |sv|%>
    <a href="/enter/companies/<%=@company.id%>/services/<%=sv.id%>" title="<%=sv.name%>"><%=sv.name%></a><br>
  <% end %>
<% end %>